- name: "Get dep for apt repo management"
  apt: 
    name={{ item }}
    state=present
  with_items:
    - python-apt
    - python-pycurl

- name: "Install apache2"
  apt:
    name=apache2
    state=present
