---
# handlers for compute role
#
- name: restart nova-compute
  systemd:
    state: restarted
    daemon_reload: yes
    name: nova-compute

- name: restart openvswitch-switch
  systemd:
    state: restarted
    daemon_reload: yes
    name: openvswitch-switch

- name: restart neutron-openvswitch-agent
  systemd:
    state: restarted
    daemon_reload: yes
    name: neutron-openvswitch-agent

- name: restart neutron-dhcp-agent
  systemd:
    state: restarted
    daemon_reload: yes
    name: neutron-dhcp-agent

- name: restart neutron-metadata-agent
  systemd:
    state: restarted
    daemon_reload: yes
    name: neutron-metadata-agent

- name: restart libvirtd
  service:
    state: restarted
    name: libvirtd
