- import_tasks: ubuntu.yml

- name: "Configuring zabbix-agent"
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart zabbix-agent
