- name: "Get apt source management dependencies"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-apt
    - python-pycurl

- name: "Install zabbix-agent"
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - zabbix-agent
