- name: "Get dep for repo-management"
  apt: 
    name={{ item }}
    state=present
  with_items:
    - python-apt
    - python-pycurl

- name: "Install rabbitmq"
  apt: 
    name={{ item }}
    state=present
  with_items:
    - rabbitmq-server
