- name: "Get apt management depend"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-apt
    - python-pycurl

- name: "Install some softwares"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - bridge-utils
    - vlan
