---
# handlers for nfs role
#
- name: restart rpcbind
  service:
    name: rpcbind
    state: restarted

- name: restart nfs
  service: 
    name=nfs-kernel-server
    state=restarted

- name: reload nfs
  service: 
    name=nfs-kernel-server
    state=reloaded
