- name: "Get dep for repo-management"
  apt: 
    name={{ item }}
    state=present
  with_items:
    - python-apt
    - python-pycurl

- name: "Install squid and htpasswd module"
  apt:
    name={{ item }}
    state=present
  with_items:
    - squid
    - python-passlib
