- import_tasks: ubuntu.yml

- name: "Config docker"
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0600
  notify: restart docker

- name: "Modify docker service script"
  lineinfile:
    path: /lib/systemd/system/docker.service
    regexp: '^ExecStartPost='
    insertbefore: '^ExecStart='
    line: 'ExecStartPost=/sbin/iptables -I FORWARD -s 0.0.0.0/0 -j ACCEPT'
  notify: restart docker
