- name: "Get dep for apt repo-management"
  apt: 
    name={{ item }}
    state=present
  with_items:
    - python-apt
    - python-pycurl

- name: "Install monit"
  apt: 
    name={{ item }}
    state=present
  with_items:
    - monit
