- name: "Install docker-ce .deb package"
  apt:
    deb: "{{ docker_deb_url }}"

- name: "Configure docker"
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart docker
