- name: "Get dep for apt repo management"
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - python-apt
    - python-pycurl

- name: "Install etcd"
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - etcd
