---
# handlers file for zabbix server role
#
- name: restart zabbix-server
  service:
    name: zabbix-server
    state: restarted

- name: restart apache2
  service:
    name: apache2
    state: restarted

- name: restart mysql
  service:
    name: mysql
    state: restarted
