- name: "Get dep for apt repo management"
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - python-apt
    - python-pycurl

- name: "Install elasticsearch"
  apt:
    deb: "{{ elasticsearch_deb_url }}" 
