---
# handlers file for mariadb role
#
- name: restart mariadb
  systemd:
    name: mysql
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart xinetd
  service:
    name: xinetd
    state: restarted
    enabled: yes
