- name: "Remove default ntp-pool"
  lineinfile:
    path: /etc/chrony/chrony.conf
    regexp: "^pool"
    state: absent
    backrefs: yes
    backup: yes
  notify: restart chrony

- name: "Add ntp-server"
  lineinfile:
    path: /etc/chrony/chrony.conf
    regexp: "^server {{ item }}"
    insertafter: EOF
    line: "server {{ item }} iburst"
    backrefs: no
    backup: yes
  with_items: "{{ ntp_servers }}"
  notify: restart chrony
