- import_tasks: ubuntu.yml

- name: "Configure haproxy"
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify:
    - reload haproxy
  tags:
    - haproxy
