- name: "Config memcached"
  lineinfile:
    path: /etc/memcached.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
    backup: yes
  with_items:
    - { regexp: "^-m", line: "-m {{ memory_size }}" }
    - { regexp: "^-l", line: "-l {{ ansible_default_ipv4.address }}" }
  notify: restart memcached
