- name: "Get apt source management dependencies"
  apt: 
    name={{ item }}
    state=present
  with_items:
    - python-apt
    - python-pycurl

- name: "Install openjdk-8-jdk and tomcat8"
  apt:
    name={{ item }}
    state=present
  with_items:
    - openjdk-8-jdk
    - tomcat8
    - tomcat8-docs
    - tomcat8-examples
    - tomcat8-admin
