- name: "Install filebeat"
  yum:
    name: "{{ filebeat_rpm }}"
    state: present 

- name: "Config filebeat"
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0600
    backup: yes
  notify: restart filebeat
