---
# handlers for kibana role
#
- name: restart kibana
  systemd:
    name: kibana
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
