---
- name: "Deploy ELK"
  
  hosts: testserver

  become: true

  pre_tasks:
    - name: "Update apt cache"
      apt: 
        update_cache=yes
        cache_valid_time=3600

  roles:
    - java
    - elasticsearch
    - logstash
    - kibana
    - filebeat
      #- rsyslog
