- name: "Get dep for apt repo-management"
  apt: 
    name={{ item }}
    state=present
  with_items:
    - python-apt
    - python-pycurl

- name: "Install nfs-kernel-server"
  apt:
    name=nfs-kernel-server
    state=present
  notify:
    - restart rpcbind
    - restart nfs
