---
# default vars file for hadoop role
#
# vars for env

hostname_prefix: bigdata
java_home: /usr/lib/jvm/java-8-openjdk-amd64
hadoop_home: /usr/local/hadoop 

# vars for tasks

hadoop_url: http://10.9.36.96/downloads/bigdata
hadoop_version: 2.9.2
hadoop_install_path: /usr/local
hadoop_conf_dir: /usr/local/hadoop/etc/hadoop

# vars for core

hadoop_tmp_dir: /usr/local/hadoop/tmp
hadoop_log_dir: /usr/local/hadoop/logs
fs_defaultfs: mycluster
io_file_buffer_size: 131072
ha_zookeeper_quorum: "bigdata-21:2181,bigdata-22:2181,bigdata-23:2181"
hdfs_user: hdfs

# vars for hdfs

dfs_replication: 3
dfs_namenode_name_dir: /usr/local/hadoop/tmp/dfs/name
dfs_hosts_exclude: /usr/local/hadoop/etc/hadoop/dfs-hosts-exclude
dfs_blocksize: 268435456
dfs_namenode_handler_count: 100

dfs_datanode_data_dir: /usr/local/hadoop/tmp/dfs/data
dfs_datanode_handler_count: 10
dfs_datanode_max_transfer_threads: 4096

dfs_nameservices: mycluster
dfs_ha_namenodes_id_1: nn1
dfs_ha_namenodes_id_2: nn2
dfs_namenode_1: bigdata-21
dfs_namenode_2: bigdata-22
dfs_journalnode_address: "bigdata-21:8485;bigdata-22:8485;bigdata-23:8485"
dfs_journalnode_edits_dir: /usr/local/hadoop/journalnode/data/ 
dfs_client_failover_proxy_provider: org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider
dfs_ha_automatic_failover_enabled: true
dfs_ha_fencing_methods: sshfence
dfs_ha_fencing_ssh_private_key_files: /home/hdfs/.ssh/id_rsa
dfs_ha_fencing_ssh_connect_timeout: 30000

# vars for mapreduce

mapreduce_framework_name: yarn
mapreduce_jobhistory_address: 0.0.0.0
mapreduce_jobhistory_webapp_address: 0.0.0.0
yarn_app_mapreduce_am_staging_dir: /tmp/hadoop-yarn/staging
mapreduce_jobhistory_done_dir: /mr-history/done
mapreduce_jobhistory_intermediate_done_dir: /mr-history/tmp
mapreduce_map_memory_mb: 1024
mapreduce_map_cpu_vcores: 1
mapreduce_reduce_memory_mb: 1024
mapreduce_reduce_cpu_vcores: 1
yarn_app_mapreduce_am_resource_mb: 1536

# vars for yarn

yarn_nodemanager_aux_services: mapreduce_shuffle
yarn_nodemanager_aux_services_mapreduce_shuffle_class: org.apache.hadoop.mapred.ShuffleHandler
yarn_resourcemanager_ha_enabled: true
yarn_resourcemanager_cluster_id: mycluster
yarn_resourcemanager_ha_rm_id_1: rm1
yarn_resourcemanager_ha_rm_id_2: rm2
yarn_resourcemanager_hostname_1: bigdata-21
yarn_resourcemanager_hostname_2: bigdata-22
yarn_resourcemanager_zk_address: "bigdata-21:2181,bigdata-22:2181,bigdata-23:2181"
yarn_log_aggregation_enable: true
yarn_log_aggregation_retain_seconds: 10800
yarn_log_aggregation_retain_check_interval_seconds: 10800
yarn_nodemanager_remote_app_log_dir: /tmp/logs
yarn_nodemanager_remote_app_log_dir_suffix: logs
yarn_log_server: 10.9.36.21
yarn_resourcemanager_scheduler_class: org.apache.hadoop.yarn.server.resourcemanager.scheduler.fair.FairScheduler
yarn_nodemanager_resource_memory_mb: 2048
yarn_nodemanager_resource_cpu_vcores: 1
yarn_scheduler_minimum_allocation_mb: 1024
yarn_scheduler_maximum_allocation_mb: 8192
yarn_scheduler_minimum_allocation_vcores: 1
yarn_scheduler_maximum_allocation_vcores: 8
yarn_am_liveness_monitor_expiry_interval_ms: 60000
yarn_resourcemanager_container_liveness_monitor_interval_ms: 60000
yarn_nm_liveness_monitor_expiry_interval_ms: 60000
yarn_resourcemanager_nodes_exclude_path: /usr/local/hadoop/etc/hadoop/yarn-nodes-exclude
