---
- hosts: testserver

  become: true

  vars:
    - node_role: first

  pre_tasks:
    - name: "Update apt cache"
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - mariadb
