- import_tasks: ubuntu.yml

- name: "Create a test database"
  mysql_db:
    name: "{{ database_name }}"
    state: present

- name: "Create a local test user"
  mysql_user:
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    priv: "{{ database_name }}.*:ALL"
    state: present

- name: "Create a remote test user"
  mysql_user:
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    priv: "{{ database_name }}.*:ALL"
    state: present
    host: "{{ remote_access_host }}"

- name: "Create a local health-check user"
  mysql_user:
    name: "{{ health_check_user }}"
    password: "{{ health_check_password }}"
    priv: "*.*:ALL"
    state: present

- name: "Configure xinetd for mariadb cluster monitor"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: "clustercheck.j2", dest: "/usr/bin/clustercheck", mode: "0755" }
    - { src: "galera-monitor.j2", dest: "/etc/xinetd.d/galera-monitor", mode: "0644" }
  notify:
    - restart xinetd
