- name: "Add some modules"
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack_ipv4

- name: "Load module at startup"
  lineinfile:
    path: /etc/modules
    state: present
    regexp: "{{ item }}"
    line: "{{ item }}"
  with_items:
    - br_netfilter
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack_ipv4
