- name: "Shut down the system swap"
  shell: "swapoff -a && touch swapoff.done"
  args:
    chdir: /root
    creates: swapoff.done

- name: "Modify fstab file"
  lineinfile:
    path: /etc/fstab
    regexp: '^/swapfile'
    state: absent

- name: "Set vm.swappiness"
  sysctl:
    name: vm.swappiness
    value: 0
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: "{{ sysctl_file }}"
