- name: "Set net.ipv4.ip_forward"
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: "{{ sysctl_file }}"

- name: "Set net.bridge.bridge-nf-call-iptables"
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: "{{ sysctl_file }}"

- name: "Set net.bridge.bridge-nf-call-ip6tables"
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: "{{ sysctl_file }}"
