- name: "Get dep for apt repo management"
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - python-apt
    - python-pycurl

- name: "Remove old software"
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: "Get dep for apt use https"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: "Add docker GPG key"
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add apt repo"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release }} stable"
    state: present
    filename: docker-ce
    update_cache: yes

- name: "Install docker"
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
