- name: "Get dep for apt repo management"
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - python-apt
    - python-pycurl

- name: "Installing common software"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nano
    - vim
    - emacs
    - net-tools
    - wget
    - apt-transport-https
    - iftop
    - tcpdump
    - chrony

- name: "Installing ceph software"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ceph
    - ceph-mds
