---
# default vars for etcd role
#
cfssl_certs_dir: /etc/cfssl/certs
#
etcd_data_dir: /var/lib/etcd/default
etcd_listen_peer_urls: https://0.0.0.0:2380
etcd_listen_client_urls: https://0.0.0.0:2379
etcd_proxy: off
etcd_initial_cluster: k8s-21=https://10.9.36.21:2380,k8s-22=https://10.9.36.22:2380,k8s-23=https://10.9.36.23:2380
etcd_initial_cluster_state: new
etcd_initial_cluster_token: k8s-etcd-cluster
etcd_ssl_dir: /etc/etcd/ssl
etcd_client_cert_auth: true
etcd_auto_tls: true
etcd_peer_client_cert_auth: true
etcd_peer_auto_tls: true
#
etcdctl_api: 3
etcdctl_endpoints: https://10.9.36.21:2379,https://10.9.36.22:2379,https://10.9.36.23:2379
