- name: "Create .ssh dir for root"
  file:
    path: /root/.ssh
    state: directory
  tags:
    - ssh

- name: "Configure passwordless ssh login for root"
  template:
    src: "/etc/ansible/sshkeys_backup/root/{{ item }}"
    dest: "/root/.ssh/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - id_rsa
    - authorized_keys
  tags:
    - ssh

- name: "Configure ssh"
  template:
    src: "/etc/ssh/{{ item }}"
    dest: "/etc/ssh/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - sshd_config
    - ssh_config
  notify:
    - reload ssh
  tags:
    - ssh
